/// MediaPipe Gesture Recognizer labels (7 trained gestures + unknown).
enum RecognizedGesture {
  closedFist('Closed_Fist'),
  openPalm('Open_Palm'),
  pointingUp('Pointing_Up'),
  thumbDown('Thumb_Down'),
  thumbUp('Thumb_Up'),
  victory('Victory'),
  iLoveYou('ILoveYou'),
  unknown('Unknown'),
  none('None');

  const RecognizedGesture(this.label);

  final String label;

  /// Parses a raw label string from MediaPipe (case-insensitive).
  static RecognizedGesture fromLabel(String? raw) {
    if (raw == null || raw.isEmpty) return RecognizedGesture.none;
    final normalized = raw.trim();
    for (final gesture in RecognizedGesture.values) {
      if (gesture == RecognizedGesture.none) continue;
      if (gesture.label.toLowerCase() == normalized.toLowerCase()) {
        return gesture;
      }
    }
    if (normalized.toLowerCase() == 'unknown') {
      return RecognizedGesture.unknown;
    }
    return RecognizedGesture.unknown;
  }

  bool get isActionable =>
      this != RecognizedGesture.unknown &&
      this != RecognizedGesture.none;
}

/// Navigation depth inside Gesture Control mode.
enum GestureNavState {
  /// User is browsing the list of rooms.
  roomsList,

  /// User confirmed a room and is browsing devices in that room.
  devicesList,

  /// User confirmed a device and can turn it ON/OFF with gestures.
  deviceAction,
}

/// Side-effects produced when the state machine accepts a gesture.
enum GestureNavActionType {
  moveNext,
  movePrevious,
  confirmSelection,
  goBack,
  turnOnDevice,
  turnOffDevice,
  jumpToRooms,
  exitMode,
  none,
}

/// Immutable snapshot of navigation UI state for the gesture screen.
class GestureNavigationSnapshot {
  const GestureNavigationSnapshot({
    required this.navState,
    required this.selectedRoomIndex,
    required this.selectedDeviceIndex,
    this.selectedRoomId,
    this.selectedDeviceId,
    this.announcement,
  });

  final GestureNavState navState;
  final int selectedRoomIndex;
  final int selectedDeviceIndex;
  final String? selectedRoomId;
  final String? selectedDeviceId;

  /// Optional TTS phrase generated by a state transition (e.g. "Ahmed Room selected").
  final String? announcement;

  GestureNavigationSnapshot copyWith({
    GestureNavState? navState,
    int? selectedRoomIndex,
    int? selectedDeviceIndex,
    String? selectedRoomId,
    String? selectedDeviceId,
    String? announcement,
    bool clearAnnouncement = false,
  }) {
    return GestureNavigationSnapshot(
      navState: navState ?? this.navState,
      selectedRoomIndex: selectedRoomIndex ?? this.selectedRoomIndex,
      selectedDeviceIndex: selectedDeviceIndex ?? this.selectedDeviceIndex,
      selectedRoomId: selectedRoomId ?? this.selectedRoomId,
      selectedDeviceId: selectedDeviceId ?? this.selectedDeviceId,
      announcement: clearAnnouncement ? null : (announcement ?? this.announcement),
    );
  }
}

/// Result returned after the state machine processes one gesture.
class GestureNavActionResult {
  const GestureNavActionResult({
    required this.action,
    required this.snapshot,
    this.deviceId,
    this.ttsMessage,
  });

  final GestureNavActionType action;
  final GestureNavigationSnapshot snapshot;
  final String? deviceId;
  final String? ttsMessage;

  bool get hasEffect => action != GestureNavActionType.none;
}
