// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyViB6jCVE0mxUYpx-qnBCV8xePDhOp8U',
    appId: '1:337778532204:web:95ffdcf63e5b940645dd49',
    messagingSenderId: '337778532204',
    projectId: 'smartassist-18d2a',
    authDomain: 'smartassist-18d2a.firebaseapp.com',
    storageBucket: 'smartassist-18d2a.firebasestorage.app',
    measurementId: 'G-LY2QL8HD8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBFHZwRTutw_u649rNW1kIWYvWfNm4qg',
    appId: '1:337778532204:android:f8486ea01906681a45dd49',
    messagingSenderId: '337778532204',
    projectId: 'smartassist-18d2a',
    storageBucket: 'smartassist-18d2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCCCBD5KoMD9hPzEmdhh30d5l5OmqwMLs',
    appId: '1:337778532204:ios:4fb5d4a7e730637745dd49',
    messagingSenderId: '337778532204',
    projectId: 'smartassist-18d2a',
    storageBucket: 'smartassist-18d2a.firebasestorage.app',
    iosClientId: '337778532204-au3p5ig2feppujv5q0dlvcmd91j2heiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCCCBD5KoMD9hPzEmdhh30d5l5OmqwMLs',
    appId: '1:337778532204:ios:4fb5d4a7e730637745dd49',
    messagingSenderId: '337778532204',
    projectId: 'smartassist-18d2a',
    storageBucket: 'smartassist-18d2a.firebasestorage.app',
    iosClientId: '337778532204-au3p5ig2feppujv5q0dlvcmd91j2heiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyViB6jCVE0mxUYpx-qnBCV8xePDhOp8U',
    appId: '1:337778532204:web:9961b66dcdc7f98345dd49',
    messagingSenderId: '337778532204',
    projectId: 'smartassist-18d2a',
    authDomain: 'smartassist-18d2a.firebaseapp.com',
    storageBucket: 'smartassist-18d2a.firebasestorage.app',
    measurementId: 'G-3VNVC6JMEH',
  );
}
